[workspace]
members = [
    "compiler/kivc",
    "compiler/kivc-ast",
    "compiler/kivc-lexer",
    "compiler/kivc-parser",
    "compiler/kivc-span",
    "compiler/kivc-diagnostics",
    "compiler/kivc-hir",
    "compiler/kivc-typeck",
    "compiler/kivc-mir",
    "compiler/kivc-codegen",
    "compiler/kivc-resolve",
    "compiler/kivc-semantic",
    "driver",
    "tools/kiv-*"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["The Kiv Project Contributors"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/kiv-lang/kiv"
repository = "https://github.com/kiv-lang/kiv"

[workspace.dependencies]
miette = { version = "7", features = ["fancy"] }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
thiserror = "2"
text-size = "1"
tower-lsp = "0.20"
env_logger = "0.11"

kivc = { path = "compiler/kivc/" }
kivc-span = { path = "compiler/kivc-span" }
kivc-diagnostics = { path = "compiler/kivc-diagnostics" }
kivc-ast = { path = "compiler/kivc-ast" }
kivc-lexer = { path = "compiler/kivc-lexer" }
kivc-parser = { path = "compiler/kivc-parser" }
kivc-typeck = { path = "compiler/kivc-typeck" }
kivc-hir = { path = "compiler/kivc-hir" }
kivc-mir = { path = "compiler/kivc-mir" }
kivc-codegen = { path = "compiler/kivc-codegen" }
